---
- name: Check network interface has a network name
  ansible.builtin.fail:
    msg: >
      The interface definition {{ interface }} has type 'network', but does not have
      a network name defined.
  when:
    - interface.type is not defined or
      interface.type == 'network'
    - interface.network is not defined

- name: Check direct interface has an interface device name
  ansible.builtin.fail:
    msg: >
      The interface definition {{ interface }} has type 'direct', but does not have
      a host source device defined.
  when:
    - interface.type is defined
    - interface.type == 'direct'
    - interface.source is not defined or
      interface.source.dev is not defined

- name: Validate network configuration requirements
  ansible.builtin.fail:
    msg: >
      {% if vm.cloud_init_enabled | default(false) | bool and not (interface.alias is defined and interface.mac is defined) %}
      When cloud-init is enabled, both 'alias' and 'mac' must be defined for all interfaces
      {% elif not (vm.cloud_init_enabled | default(false) | bool) and (interface.address is defined or interface.gateway is defined or interface.nameservers is defined) %}
      Cloud-init must be enabled when configuring network settings (address, gateway, or nameservers)
      {% endif %}
  when:
    - vm.cloud_init_enabled | default(false) | bool and not (interface.alias is defined and interface.mac is defined) or
      not (vm.cloud_init_enabled | default(false) | bool) and (interface.address is defined or interface.gateway is defined or interface.nameservers is defined)