---
name: Publish Ansible Role
'on':
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
jobs:
  publish_role:
    uses: stackhpc/.github/.github/workflows/publish-role.yml@main
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
